const mongoose = require('mongoose');
require('dotenv').config({ path: require('path').join(__dirname, '.env') });

const Bus = require('./src/models/Bus');

// Real sample bus images from Unsplash (free to use)
const BUS_IMAGES = [
  'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400&h=250&fit=crop',
  'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=400&h=250&fit=crop',
  'https://images.unsplash.com/photo-1592990772922-8d5df0f78e1b?w=400&h=250&fit=crop',
  'https://images.unsplash.com/photo-1580048915913-e4b8f2d21c4e?w=400&h=250&fit=crop',
  'https://images.unsplash.com/photo-1572953109917-ca05435829b6?w=400&h=250&fit=crop',
  'https://images.unsplash.com/photo-1551703595-9e7a32a3cd41?w=400&h=250&fit=crop',
  'https://images.unsplash.com/photo-1546614042-7df3c24c3544?w=400&h=250&fit=crop',
  'https://images.unsplash.com/photo-1596108188991-e4bbd4a20edb?w=400&h=250&fit=crop',
  'https://images.unsplash.com/photo-1595535884902-f69fa8e7b8f2?w=400&h=250&fit=crop',
  'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?w=400&h=250&fit=crop',
];

const busesData = [
  // ===== ROUTE: Mumbai → Pune =====
  {
    busName: 'Shivneri Express',
    operator: 'MSRTC',
    busType: 'AC',
    from: 'Mumbai',
    to: 'Pune',
    fromCity: 'Mumbai',
    toCity: 'Pune',
    departureTime: '06:30',
    arrivalTime: '10:45',
    duration: '4h 15m',
    totalSeats: 40,
    availableSeats: 12,
    fare: 650,
    rating: 4.5,
    reviews: 892,
    amenities: ['WiFi', 'Charging Point', 'Water Bottle', 'Blanket', 'Reading Light', 'Reclining Seats'],
    boardingPoint: { name: 'Dadar Station', address: 'Dadar, Mumbai', time: '06:30' },
    droppingPoint: { name: 'Shivaji Nagar', address: 'Shivaji Nagar, Pune', time: '10:45' },
    stops: [
      { name: 'Borivali', time: '07:15', type: 'boarding' },
      { name: 'Thane', time: '08:00', type: 'stop' },
      { name: 'Khandala Ghat', time: '09:15', type: 'stop' },
    ],
    image: BUS_IMAGES[0],
    cancellationPolicy: 'Free cancellation up to 4 hours before departure',
    bookedSeats: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    busName: 'Deccan Queen',
    operator: 'Purple Travels',
    busType: 'Sleeper',
    from: 'Mumbai',
    to: 'Pune',
    fromCity: 'Mumbai',
    toCity: 'Pune',
    departureTime: '22:00',
    arrivalTime: '05:30',
    duration: '7h 30m',
    totalSeats: 32,
    availableSeats: 8,
    fare: 850,
    rating: 4.2,
    reviews: 634,
    amenities: ['WiFi', 'Blanket', 'Water Bottle', 'Charging Point', 'Pillow', 'Reading Light', 'AC'],
    boardingPoint: { name: 'CBD Belapur', address: 'CBD Belapur, Navi Mumbai', time: '22:00' },
    droppingPoint: { name: 'Swargate', address: 'Swargate, Pune', time: '05:30' },
    stops: [
      { name: 'Panvel', time: '22:45', type: 'boarding' },
      { name: 'Lonavala', time: '01:30', type: 'stop' },
    ],
    image: BUS_IMAGES[1],
    cancellationPolicy: 'Free cancellation up to 6 hours before departure',
    bookedSeats: [1, 2, 3, 5, 7, 9],
  },
  {
    busName: 'Indraprastha Travels',
    operator: 'Indraprastha',
    busType: 'Non-AC',
    from: 'Mumbai',
    to: 'Pune',
    fromCity: 'Mumbai',
    toCity: 'Pune',
    departureTime: '07:45',
    arrivalTime: '12:30',
    duration: '4h 45m',
    totalSeats: 50,
    availableSeats: 25,
    fare: 350,
    rating: 3.8,
    reviews: 421,
    amenities: ['Water Bottle', 'Charging Point'],
    boardingPoint: { name: 'Bandra East', address: 'Bandra East, Mumbai', time: '07:45' },
    droppingPoint: { name: 'Pune Station', address: 'Pune Junction', time: '12:30' },
    stops: [
      { name: 'Kurla', time: '08:15', type: 'boarding' },
      { name: 'Chembur', time: '08:45', type: 'boarding' },
    ],
    image: BUS_IMAGES[2],
    cancellationPolicy: 'No cancellation allowed',
    bookedSeats: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
  },
  {
    busName: 'Neeta AC Seater',
    operator: 'Neeta Travels',
    busType: 'Seater',
    from: 'Mumbai',
    to: 'Pune',
    fromCity: 'Mumbai',
    toCity: 'Pune',
    departureTime: '08:00',
    arrivalTime: '12:15',
    duration: '4h 15m',
    totalSeats: 45,
    availableSeats: 18,
    fare: 550,
    rating: 4.0,
    reviews: 1567,
    amenities: ['WiFi', 'Water Bottle', 'Charging Point', 'Blanket', 'Snacks', 'AC'],
    boardingPoint: { name: 'Andheri East', address: 'Andheri East, Mumbai', time: '08:00' },
    droppingPoint: { name: 'Shivaji Nagar', address: 'Shivaji Nagar, Pune', time: '12:15' },
    stops: [
      { name: 'Vile Parle', time: '08:20', type: 'boarding' },
      { name: 'Dadar', time: '08:50', type: 'boarding' },
    ],
    image: BUS_IMAGES[3],
    cancellationPolicy: 'Free cancellation up to 2 hours before departure',
    bookedSeats: [2, 4, 6, 8],
  },
  {
    busName: 'Sahara Night Rider',
    operator: 'Sahara Travels',
    busType: 'Sleeper',
    from: 'Mumbai',
    to: 'Pune',
    fromCity: 'Mumbai',
    toCity: 'Pune',
    departureTime: '23:30',
    arrivalTime: '06:00',
    duration: '6h 30m',
    totalSeats: 36,
    availableSeats: 6,
    fare: 900,
    rating: 4.3,
    reviews: 445,
    amenities: ['WiFi', 'Blanket', 'Water Bottle', 'Charging Point', 'Pillow', 'Reading Light', 'Dinner'],
    boardingPoint: { name: 'Kurla Terminal', address: 'Kurla, Mumbai', time: '23:30' },
    droppingPoint: { name: 'Swargate', address: 'Swargate, Pune', time: '06:00' },
    stops: [],
    image: BUS_IMAGES[4],
    cancellationPolicy: 'Free cancellation up to 12 hours before departure',
    bookedSeats: [1, 2, 3, 4, 5],
  },
  {
    busName: 'Premium Express',
    operator: 'Premium Travels',
    busType: 'AC',
    from: 'Mumbai',
    to: 'Pune',
    fromCity: 'Mumbai',
    toCity: 'Pune',
    departureTime: '10:00',
    arrivalTime: '14:30',
    duration: '4h 30m',
    totalSeats: 42,
    availableSeats: 20,
    fare: 750,
    rating: 4.7,
    reviews: 2341,
    amenities: ['WiFi', 'Charging Point', 'Blanket', 'Water Bottle', 'Reading Light', 'Reclining Seats', 'Snacks', 'Dinner'],
    boardingPoint: { name: 'Borivali West', address: 'Borivali West, Mumbai', time: '10:00' },
    droppingPoint: { name: 'Hinjewadi', address: 'Hinjewadi Phase 1, Pune', time: '14:30' },
    stops: [
      { name: 'Kandivali', time: '10:15', type: 'boarding' },
      { name: 'Dahisar', time: '10:30', type: 'boarding' },
      { name: 'Bandra', time: '11:15', type: 'stop' },
    ],
    image: BUS_IMAGES[5],
    cancellationPolicy: 'Free cancellation up to 1 hour before departure',
    bookedSeats: [1, 3, 5, 7, 9, 11],
  },
  {
    busName: 'City Link Seater',
    operator: 'City Link',
    busType: 'Non-AC',
    from: 'Mumbai',
    to: 'Pune',
    fromCity: 'Mumbai',
    toCity: 'Pune',
    departureTime: '05:00',
    arrivalTime: '09:45',
    duration: '4h 45m',
    totalSeats: 52,
    availableSeats: 30,
    fare: 300,
    rating: 3.5,
    reviews: 189,
    amenities: ['Water Bottle'],
    boardingPoint: { name: 'Dadar', address: 'Dadar, Mumbai', time: '05:00' },
    droppingPoint: { name: 'Pune Station', address: 'Pune Junction', time: '09:45' },
    stops: [],
    image: BUS_IMAGES[6],
    cancellationPolicy: 'No cancellation',
    bookedSeats: [],
  },

  // ===== ROUTE: Delhi → Jaipur =====
  {
    busName: 'Rajdhani Deluxe',
    operator: 'RSRTC',
    busType: 'AC',
    from: 'Delhi',
    to: 'Jaipur',
    fromCity: 'Delhi',
    toCity: 'Jaipur',
    departureTime: '07:00',
    arrivalTime: '12:30',
    duration: '5h 30m',
    totalSeats: 40,
    availableSeats: 15,
    fare: 700,
    rating: 4.4,
    reviews: 1987,
    amenities: ['WiFi', 'Charging Point', 'Water Bottle', 'Blanket', 'Reading Light', 'Reclining Seats'],
    boardingPoint: { name: 'ISBT Kashmere Gate', address: 'Kashmere Gate, Delhi', time: '07:00' },
    droppingPoint: { name: 'Sindhi Camp', address: 'Sindhi Camp, Jaipur', time: '12:30' },
    stops: [
      { name: 'Rohini', time: '07:30', type: 'boarding' },
      { name: 'Dwarka', time: '08:00', type: 'boarding' },
      { name: 'Gurgaon', time: '08:45', type: 'stop' },
    ],
    image: BUS_IMAGES[7],
    cancellationPolicy: 'Free cancellation up to 4 hours before departure',
    bookedSeats: [1, 2, 3, 4, 5],
  },
  {
    busName: 'Rajasthan Link',
    operator: 'Rajasthan Travels',
    busType: 'Sleeper',
    from: 'Delhi',
    to: 'Jaipur',
    fromCity: 'Delhi',
    toCity: 'Jaipur',
    departureTime: '22:00',
    arrivalTime: '05:00',
    duration: '7h',
    totalSeats: 36,
    availableSeats: 10,
    fare: 950,
    rating: 4.1,
    reviews: 876,
    amenities: ['WiFi', 'Blanket', 'Water Bottle', 'Charging Point', 'Pillow'],
    boardingPoint: { name: 'Sarai Kale Khan', address: 'Sarai Kale Khan, Delhi', time: '22:00' },
    droppingPoint: { name: 'Sindhi Camp', address: 'Sindhi Camp, Jaipur', time: '05:00' },
    stops: [
      { name: 'Dhaula Kuan', time: '22:30', type: 'boarding' },
    ],
    image: BUS_IMAGES[8],
    cancellationPolicy: 'Free cancellation up to 8 hours before departure',
    bookedSeats: [1, 2, 3, 4, 5, 6],
  },
  {
    busName: 'Pink City Express',
    operator: 'Travels Hub',
    busType: 'Seater',
    from: 'Delhi',
    to: 'Jaipur',
    fromCity: 'Delhi',
    toCity: 'Jaipur',
    departureTime: '14:00',
    arrivalTime: '19:30',
    duration: '5h 30m',
    totalSeats: 45,
    availableSeats: 22,
    fare: 500,
    rating: 3.9,
    reviews: 654,
    amenities: ['WiFi', 'Water Bottle', 'Charging Point'],
    boardingPoint: { name: 'Anand Vihar', address: 'Anand Vihar ISBT, Delhi', time: '14:00' },
    droppingPoint: { name: 'Mansarovar', address: 'Mansarovar, Jaipur', time: '19:30' },
    stops: [
      { name: 'Laxmi Nagar', time: '14:20', type: 'boarding' },
    ],
    image: BUS_IMAGES[9],
    cancellationPolicy: 'Free cancellation up to 2 hours before departure',
    bookedSeats: [5, 10, 15, 20],
  },
  {
    busName: 'AC Volvo Seater',
    operator: 'Volvo Travels',
    busType: 'Seater',
    from: 'Delhi',
    to: 'Jaipur',
    fromCity: 'Delhi',
    toCity: 'Jaipur',
    departureTime: '06:30',
    arrivalTime: '11:45',
    duration: '5h 15m',
    totalSeats: 40,
    availableSeats: 28,
    fare: 800,
    rating: 4.6,
    reviews: 3120,
    amenities: ['WiFi', 'Charging Point', 'Blanket', 'Water Bottle', 'Reading Light', 'Reclining Seats', 'Snacks', 'AC'],
    boardingPoint: { name: 'Majan Ka Tila', address: 'Majan Ka Tila, Delhi', time: '06:30' },
    droppingPoint: { name: 'Jaipur Airport', address: 'Sanganer, Jaipur', time: '11:45' },
    stops: [],
    image: BUS_IMAGES[0],
    cancellationPolicy: 'Free cancellation up to 3 hours before departure',
    bookedSeats: [1, 2, 3],
  },
  {
    busName: 'Budget Travels',
    operator: 'Budget Bus',
    busType: 'Non-AC',
    from: 'Delhi',
    to: 'Jaipur',
    fromCity: 'Delhi',
    toCity: 'Jaipur',
    departureTime: '15:30',
    arrivalTime: '21:30',
    duration: '6h',
    totalSeats: 50,
    availableSeats: 35,
    fare: 400,
    rating: 3.4,
    reviews: 234,
    amenities: ['Water Bottle', 'Charging Point'],
    boardingPoint: { name: 'ISBT Anand Vihar', address: 'Anand Vihar, Delhi', time: '15:30' },
    droppingPoint: { name: 'Sindhi Camp', address: 'Sindhi Camp, Jaipur', time: '21:30' },
    stops: [],
    image: BUS_IMAGES[1],
    cancellationPolicy: 'No cancellation allowed',
    bookedSeats: [],
  },

  // ===== ROUTE: Bangalore → Hyderabad =====
  {
    busName: 'Namma Metro AC',
    operator: 'KSRTC',
    busType: 'AC',
    from: 'Bangalore',
    to: 'Hyderabad',
    fromCity: 'Bangalore',
    toCity: 'Hyderabad',
    departureTime: '08:00',
    arrivalTime: '16:00',
    duration: '8h',
    totalSeats: 40,
    availableSeats: 14,
    fare: 950,
    rating: 4.3,
    reviews: 1456,
    amenities: ['WiFi', 'Charging Point', 'Blanket', 'Water Bottle', 'Reading Light', 'Reclining Seats', 'Snacks', 'Dinner'],
    boardingPoint: { name: 'Majestic Bus Stand', address: 'Majestic, Bangalore', time: '08:00' },
    droppingPoint: { name: 'MGBS Hyderabad', address: 'MGBS, Hyderabad', time: '16:00' },
    stops: [
      { name: 'Electronic City', time: '08:45', type: 'boarding' },
      { name: 'Attibele', time: '09:30', type: 'boarding' },
      { name: 'Chikkaballapur', time: '10:30', type: 'stop' },
    ],
    image: BUS_IMAGES[2],
    cancellationPolicy: 'Free cancellation up to 6 hours before departure',
    bookedSeats: [3, 6, 9, 12, 15],
  },
  {
    busName: 'Royal Cruiser',
    operator: 'Orange Travels',
    busType: 'Sleeper',
    from: 'Bangalore',
    to: 'Hyderabad',
    fromCity: 'Bangalore',
    toCity: 'Hyderabad',
    departureTime: '20:00',
    arrivalTime: '06:00',
    duration: '10h',
    totalSeats: 32,
    availableSeats: 5,
    fare: 1200,
    rating: 4.5,
    reviews: 2234,
    amenities: ['WiFi', 'Blanket', 'Water Bottle', 'Charging Point', 'Pillow', 'Reading Light', 'Dinner', 'Snacks'],
    boardingPoint: { name: 'Koramangala', address: 'Koramangala, Bangalore', time: '20:00' },
    droppingPoint: { name: 'Gachibowli', address: 'Gachibowli, Hyderabad', time: '06:00' },
    stops: [
      { name: 'HSR Layout', time: '20:20', type: 'boarding' },
      { name: 'Silk Board', time: '20:40', type: 'boarding' },
    ],
    image: BUS_IMAGES[3],
    cancellationPolicy: 'Free cancellation up to 12 hours before departure',
    bookedSeats: [1, 2, 3, 4, 5, 6, 7],
  },
  {
    busName: 'Deccan Seater',
    operator: 'Deccan Travels',
    busType: 'Seater',
    from: 'Bangalore',
    to: 'Hyderabad',
    fromCity: 'Bangalore',
    toCity: 'Hyderabad',
    departureTime: '06:30',
    arrivalTime: '14:30',
    duration: '8h',
    totalSeats: 45,
    availableSeats: 20,
    fare: 700,
    rating: 3.7,
    reviews: 567,
    amenities: ['WiFi', 'Water Bottle', 'Charging Point'],
    boardingPoint: { name: 'Shivajinagar', address: 'Shivajinagar, Bangalore', time: '06:30' },
    droppingPoint: { name: 'Jubilee Hills', address: 'Jubilee Hills, Hyderabad', time: '14:30' },
    stops: [
      { name: 'Madiwala', time: '07:00', type: 'boarding' },
    ],
    image: BUS_IMAGES[4],
    cancellationPolicy: 'Free cancellation up to 4 hours before departure',
    bookedSeats: [5, 10, 15],
  },
  {
    busName: 'Rainbow AC',
    operator: 'Rainbow Tours',
    busType: 'Sleeper',
    from: 'Bangalore',
    to: 'Hyderabad',
    fromCity: 'Bangalore',
    toCity: 'Hyderabad',
    departureTime: '21:00',
    arrivalTime: '07:00',
    duration: '10h',
    totalSeats: 36,
    availableSeats: 12,
    fare: 1100,
    rating: 4.1,
    reviews: 890,
    amenities: ['WiFi', 'Charging Point', 'Blanket', 'Water Bottle', 'Pillow', 'Reading Light', 'AC'],
    boardingPoint: { name: 'Marathahalli', address: 'Marathahalli, Bangalore', time: '21:00' },
    droppingPoint: { name: 'Hitech City', address: 'Hitech City, Hyderabad', time: '07:00' },
    stops: [
      { name: 'Whitefield', time: '21:30', type: 'boarding' },
    ],
    image: BUS_IMAGES[5],
    cancellationPolicy: 'Free cancellation up to 6 hours before departure',
    bookedSeats: [2, 4, 6, 8, 10],
  },
  {
    busName: 'Saver Non-AC',
    operator: 'Saver Travels',
    busType: 'Non-AC',
    from: 'Bangalore',
    to: 'Hyderabad',
    fromCity: 'Bangalore',
    toCity: 'Hyderabad',
    departureTime: '04:30',
    arrivalTime: '14:00',
    duration: '9h 30m',
    totalSeats: 50,
    availableSeats: 40,
    fare: 500,
    rating: 3.2,
    reviews: 123,
    amenities: ['Water Bottle'],
    boardingPoint: { name: 'KBS Bus Stand', address: 'Kalasipalya, Bangalore', time: '04:30' },
    droppingPoint: { name: 'Koti', address: 'Koti, Hyderabad', time: '14:00' },
    stops: [],
    image: BUS_IMAGES[6],
    cancellationPolicy: 'No cancellation',
    bookedSeats: [],
  },

  // ===== ROUTE: Chennai → Bangalore =====
  {
    busName: 'Coromandel Express',
    operator: 'SETC',
    busType: 'AC',
    from: 'Chennai',
    to: 'Bangalore',
    fromCity: 'Chennai',
    toCity: 'Bangalore',
    departureTime: '06:00',
    arrivalTime: '12:00',
    duration: '6h',
    totalSeats: 40,
    availableSeats: 18,
    fare: 600,
    rating: 4.2,
    reviews: 1678,
    amenities: ['WiFi', 'Charging Point', 'Water Bottle', 'Blanket', 'Reading Light'],
    boardingPoint: { name: 'Koyambedu', address: 'Koyambedu, Chennai', time: '06:00' },
    droppingPoint: { name: 'Shantinagar', address: 'Shantinagar, Bangalore', time: '12:00' },
    stops: [
      { name: 'Tambaram', time: '06:45', type: 'boarding' },
      { name: 'Kanchipuram', time: '07:45', type: 'stop' },
    ],
    image: BUS_IMAGES[7],
    cancellationPolicy: 'Free cancellation up to 4 hours before departure',
    bookedSeats: [1, 3, 5, 7],
  },
  {
    busName: 'Silk City AC',
    operator: 'KPN Travels',
    busType: 'Seater',
    from: 'Chennai',
    to: 'Bangalore',
    fromCity: 'Chennai',
    toCity: 'Bangalore',
    departureTime: '22:00',
    arrivalTime: '06:00',
    duration: '8h',
    totalSeats: 36,
    availableSeats: 10,
    fare: 850,
    rating: 4.4,
    reviews: 2134,
    amenities: ['WiFi', 'Blanket', 'Water Bottle', 'Charging Point', 'Pillow', 'Reading Light', 'Snacks', 'AC'],
    boardingPoint: { name: 'Chennai Central', address: 'Chennai Central, Chennai', time: '22:00' },
    droppingPoint: { name: 'Majestic', address: 'Majestic, Bangalore', time: '06:00' },
    stops: [
      { name: 'Anna Nagar', time: '22:20', type: 'boarding' },
    ],
    image: BUS_IMAGES[8],
    cancellationPolicy: 'Free cancellation up to 8 hours before departure',
    bookedSeats: [1, 2, 3, 4, 5],
  },
  {
    busName: 'Budget Connect',
    operator: 'Budget Buses',
    busType: 'Non-AC',
    from: 'Chennai',
    to: 'Bangalore',
    fromCity: 'Chennai',
    toCity: 'Bangalore',
    departureTime: '12:30',
    arrivalTime: '19:30',
    duration: '7h',
    totalSeats: 50,
    availableSeats: 32,
    fare: 380,
    rating: 3.3,
    reviews: 345,
    amenities: ['Water Bottle', 'Charging Point'],
    boardingPoint: { name: 'Chennai Mofussil', address: 'CMBT, Chennai', time: '12:30' },
    droppingPoint: { name: 'KR Market', address: 'KR Market, Bangalore', time: '19:30' },
    stops: [],
    image: BUS_IMAGES[9],
    cancellationPolicy: 'No cancellation allowed',
    bookedSeats: [],
  },
  {
    busName: 'Night Rider Sleeper',
    operator: 'Night Travels',
    busType: 'Sleeper',
    from: 'Chennai',
    to: 'Bangalore',
    fromCity: 'Chennai',
    toCity: 'Bangalore',
    departureTime: '23:30',
    arrivalTime: '08:00',
    duration: '8h 30m',
    totalSeats: 32,
    availableSeats: 8,
    fare: 950,
    rating: 4.0,
    reviews: 765,
    amenities: ['WiFi', 'Blanket', 'Water Bottle', 'Charging Point', 'Pillow'],
    boardingPoint: { name: 'T Nagar', address: 'T Nagar, Chennai', time: '23:30' },
    droppingPoint: { name: 'Electronic City', address: 'Electronic City, Bangalore', time: '08:00' },
    stops: [
      { name: 'Guindy', time: '23:45', type: 'boarding' },
    ],
    image: BUS_IMAGES[0],
    cancellationPolicy: 'Free cancellation up to 12 hours before departure',
    bookedSeats: [1, 2, 3, 4],
  },

  // ===== ROUTE: Ahmedabad → Vadodara =====
  {
    busName: 'Gujarat Express',
    operator: 'GSRTC',
    busType: 'AC',
    from: 'Ahmedabad',
    to: 'Vadodara',
    fromCity: 'Ahmedabad',
    toCity: 'Vadodara',
    departureTime: '09:00',
    arrivalTime: '12:15',
    duration: '3h 15m',
    totalSeats: 40,
    availableSeats: 22,
    fare: 400,
    rating: 4.1,
    reviews: 987,
    amenities: ['WiFi', 'Charging Point', 'Water Bottle', 'Blanket', 'Reading Light'],
    boardingPoint: { name: 'Geeta Mandir', address: 'Geeta Mandir, Ahmedabad', time: '09:00' },
    droppingPoint: { name: 'Vadodara Central', address: 'Vadodara Central, Vadodara', time: '12:15' },
    stops: [
      { name: 'Nadiad', time: '10:15', type: 'stop' },
      { name: 'Anand', time: '10:45', type: 'stop' },
    ],
    image: BUS_IMAGES[1],
    cancellationPolicy: 'Free cancellation up to 2 hours before departure',
    bookedSeats: [1, 2, 3],
  },
  {
    busName: 'Somnath Deluxe',
    operator: 'Somnath Travels',
    busType: 'Seater',
    from: 'Ahmedabad',
    to: 'Vadodara',
    fromCity: 'Ahmedabad',
    toCity: 'Vadodara',
    departureTime: '16:00',
    arrivalTime: '19:30',
    duration: '3h 30m',
    totalSeats: 45,
    availableSeats: 28,
    fare: 320,
    rating: 3.6,
    reviews: 432,
    amenities: ['Water Bottle', 'Charging Point'],
    boardingPoint: { name: 'Kalupur', address: 'Kalupur, Ahmedabad', time: '16:00' },
    droppingPoint: { name: 'Alkapuri', address: 'Alkapuri, Vadodara', time: '19:30' },
    stops: [],
    image: BUS_IMAGES[2],
    cancellationPolicy: 'Free cancellation up to 1 hour before departure',
    bookedSeats: [],
  },
  {
    busName: 'Mahakali Non-AC',
    operator: 'Mahakali Travels',
    busType: 'Non-AC',
    from: 'Ahmedabad',
    to: 'Vadodara',
    fromCity: 'Ahmedabad',
    toCity: 'Vadodara',
    departureTime: '07:30',
    arrivalTime: '11:15',
    duration: '3h 45m',
    totalSeats: 50,
    availableSeats: 38,
    fare: 250,
    rating: 3.1,
    reviews: 198,
    amenities: ['Water Bottle'],
    boardingPoint: { name: 'Astodia Gate', address: 'Astodia, Ahmedabad', time: '07:30' },
    droppingPoint: { name: 'Fatehgunj', address: 'Fatehgunj, Vadodara', time: '11:15' },
    stops: [],
    image: BUS_IMAGES[3],
    cancellationPolicy: 'No cancellation',
    bookedSeats: [],
  },
  {
    busName: 'Royal Sleeper',
    operator: 'Royal Travels',
    busType: 'Sleeper',
    from: 'Ahmedabad',
    to: 'Vadodara',
    fromCity: 'Ahmedabad',
    toCity: 'Vadodara',
    departureTime: '23:00',
    arrivalTime: '04:30',
    duration: '5h 30m',
    totalSeats: 36,
    availableSeats: 15,
    fare: 600,
    rating: 4.0,
    reviews: 543,
    amenities: ['WiFi', 'Blanket', 'Water Bottle', 'Charging Point', 'Pillow', 'Reading Light'],
    boardingPoint: { name: 'Ahmedabad Station', address: 'Ahmedabad Railway Station', time: '23:00' },
    droppingPoint: { name: 'Vadodara Station', address: 'Vadodara Railway Station', time: '04:30' },
    stops: [],
    image: BUS_IMAGES[4],
    cancellationPolicy: 'Free cancellation up to 6 hours before departure',
    bookedSeats: [1, 2, 3, 4, 5, 6, 7],
  },

  // ===== ADDITIONAL ROUTES FOR VARIETY =====
  {
    busName: 'Green Chariot',
    operator: 'Green Travels',
    busType: 'AC',
    from: 'Pune',
    to: 'Mumbai',
    fromCity: 'Pune',
    toCity: 'Mumbai',
    departureTime: '07:00',
    arrivalTime: '11:30',
    duration: '4h 30m',
    totalSeats: 40,
    availableSeats: 20,
    fare: 600,
    rating: 4.3,
    reviews: 1123,
    amenities: ['WiFi', 'Charging Point', 'Blanket', 'Water Bottle', 'Reading Light', 'Reclining Seats'],
    boardingPoint: { name: 'Swargate', address: 'Swargate, Pune', time: '07:00' },
    droppingPoint: { name: 'Dadar', address: 'Dadar, Mumbai', time: '11:30' },
    stops: [
      { name: 'Shivaji Nagar', time: '07:15', type: 'boarding' },
    ],
    image: BUS_IMAGES[5],
    cancellationPolicy: 'Free cancellation up to 4 hours before departure',
    bookedSeats: [1, 2, 3, 4, 5],
  },
  {
    busName: 'Blue Star AC',
    operator: 'Blue Star',
    busType: 'Sleeper',
    from: 'Hyderabad',
    to: 'Bangalore',
    fromCity: 'Hyderabad',
    toCity: 'Bangalore',
    departureTime: '20:30',
    arrivalTime: '06:30',
    duration: '10h',
    totalSeats: 36,
    availableSeats: 11,
    fare: 1050,
    rating: 4.4,
    reviews: 1876,
    amenities: ['WiFi', 'Charging Point', 'Blanket', 'Water Bottle', 'Pillow', 'Reading Light', 'Dinner', 'AC'],
    boardingPoint: { name: 'MGBS', address: 'MGBS, Hyderabad', time: '20:30' },
    droppingPoint: { name: 'Majestic', address: 'Majestic, Bangalore', time: '06:30' },
    stops: [
      { name: 'KPHB', time: '20:50', type: 'boarding' },
      { name: 'Kukatpally', time: '21:10', type: 'boarding' },
    ],
    image: BUS_IMAGES[6],
    cancellationPolicy: 'Free cancellation up to 8 hours before departure',
    bookedSeats: [2, 4, 6],
  },
  {
    busName: 'Pioneer Seater',
    operator: 'Pioneer Travels',
    busType: 'Seater',
    from: 'Jaipur',
    to: 'Delhi',
    fromCity: 'Jaipur',
    toCity: 'Delhi',
    departureTime: '13:00',
    arrivalTime: '18:30',
    duration: '5h 30m',
    totalSeats: 45,
    availableSeats: 25,
    fare: 550,
    rating: 3.8,
    reviews: 765,
    amenities: ['WiFi', 'Water Bottle', 'Charging Point', 'Snacks'],
    boardingPoint: { name: 'Sindhi Camp', address: 'Sindhi Camp, Jaipur', time: '13:00' },
    droppingPoint: { name: 'ISBT Kashmere Gate', address: 'Kashmere Gate, Delhi', time: '18:30' },
    stops: [],
    image: BUS_IMAGES[7],
    cancellationPolicy: 'Free cancellation up to 3 hours before departure',
    bookedSeats: [10, 20],
  },
  {
    busName: 'Quick Shuttle',
    operator: 'Quick Travels',
    busType: 'Non-AC',
    from: 'Bangalore',
    to: 'Chennai',
    fromCity: 'Bangalore',
    toCity: 'Chennai',
    departureTime: '05:00',
    arrivalTime: '12:00',
    duration: '7h',
    totalSeats: 50,
    availableSeats: 33,
    fare: 450,
    rating: 3.5,
    reviews: 432,
    amenities: ['Water Bottle', 'Charging Point'],
    boardingPoint: { name: 'Majestic', address: 'Majestic, Bangalore', time: '05:00' },
    droppingPoint: { name: 'Koyambedu', address: 'Koyambedu, Chennai', time: '12:00' },
    stops: [
      { name: 'Hosur', time: '06:00', type: 'boarding' },
    ],
    image: BUS_IMAGES[8],
    cancellationPolicy: 'No cancellation allowed',
    bookedSeats: [],
  },
  {
    busName: 'Luxury King',
    operator: 'Luxury Travels',
    busType: 'AC',
    from: 'Mumbai',
    to: 'Delhi',
    fromCity: 'Mumbai',
    toCity: 'Delhi',
    departureTime: '17:00',
    arrivalTime: '10:00',
    duration: '17h',
    totalSeats: 36,
    availableSeats: 9,
    fare: 1800,
    rating: 4.6,
    reviews: 3456,
    amenities: ['WiFi', 'Charging Point', 'Blanket', 'Water Bottle', 'Reading Light', 'Reclining Seats', 'Snacks', 'Dinner', 'Pillow'],
    boardingPoint: { name: 'Borivali', address: 'Borivali, Mumbai', time: '17:00' },
    droppingPoint: { name: 'ISBT Kashmere Gate', address: 'Kashmere Gate, Delhi', time: '10:00' },
    stops: [
      { name: 'Dadar', time: '17:45', type: 'boarding' },
      { name: 'Thane', time: '18:30', type: 'boarding' },
      { name: 'Surat', time: '21:30', type: 'stop' },
      { name: 'Udaipur', time: '03:00', type: 'stop' },
    ],
    image: BUS_IMAGES[9],
    cancellationPolicy: 'Free cancellation up to 24 hours before departure',
    bookedSeats: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  },
];

async function seedBuses() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    // Delete existing buses
    const deleteResult = await Bus.deleteMany({});
    console.log(`Deleted ${deleteResult.deletedCount} existing buses`);

    // Insert seed data
    const inserted = await Bus.insertMany(busesData);
    console.log(`Successfully inserted ${inserted.length} buses`);

    // Print summary
    console.log('\n=== SEED SUMMARY ===');
    console.log('Routes covered:');
    const routes = [...new Set(busesData.map(b => `${b.from} → ${b.to}`))];
    routes.forEach(r => console.log(`  • ${r}`));
    
    console.log('\nBus types available:');
    const types = [...new Set(busesData.map(b => b.busType))];
    types.forEach(t => console.log(`  • ${t}`));
    
    console.log('\nAmenities filterable:');
    const amenityOptions = ['WiFi', 'Charging Point', 'Blanket', 'Water Bottle'];
    amenityOptions.forEach(a => {
      const count = busesData.filter(b => b.amenities.some(am => am.toLowerCase().includes(a.toLowerCase()))).length;
      console.log(`  • ${a}: ${count} buses have this`);
    });

    console.log('\nBus type filter match check (exact match with frontend options):');
    const frontendTypeOptions = ['Seater', 'Sleeper', 'AC', 'Non-AC'];
    frontendTypeOptions.forEach(t => {
      const count = busesData.filter(b => b.busType === t).length;
      console.log(`  • "${t}": ${count} buses will match`);
    });

    console.log(`\nFare range: ₹${Math.min(...busesData.map(b => b.fare))} to ₹${Math.max(...busesData.map(b => b.fare))}`);
    console.log(`\n✅ All buses have real sample images from Unsplash`);
    
    await mongoose.disconnect();
    console.log('\n✅ Seed completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error.message);
    process.exit(1);
  }
}

seedBuses();